## Create dataset grouped_entities

Contais columns ID, role and entity. Entity is a string with semicolon-separated entities aggregated per ID and role.

For example, say roles_df has the following rows:

| index | ID  | role   | entity       |
|--------|-----|--------|-------------|
| 0      | 100 | victim | the planet  |
| 1      | 100 | victim | humanity    |


Then grouped_entities will have the next row:


| index | ID  | role   | entities              |
|-------|-----|--------|---------------------  |
| 0     | 100 | victim | the planet; humanity  |

In [1]:
import pandas as pd

In [ ]:
roles_df = pd.read_csv(
    "../data/interim/roles_df.tsv", 
    sep='\t',
    encoding='ascii',
    encoding_errors='ignore'  # Skip non-ASCII characters
    )

No entity contains a semicolon

In [21]:
roles_df[roles_df.entity.str.contains(";")]

Empty DataFrame
Columns: [ID, entity, role]
Index: []

Per ID and narrative role, concatenate entities separated by a semicolon

In [11]:
# list didn't work, saved really funny
# grouped_entities = roles_df.groupby(['ID', 'role'])['entity'].agg(list).reset_index()

grouped_entities = roles_df.groupby(['ID', 'role'])['entity'].agg(lambda x: '; '.join(x)).reset_index()

grouped_entities.head()

   ID     role                                             entity
0   0   victim                        people who are unscientific
1   0  villain                                  climate alarmists
2   2   victim                                           the U.S.
3   2  villain  climate alarmism; Democratic New York Rep. Ale...
4   3   victim                            a city built on a swamp

Rename column entity to *entities*

In [12]:
grouped_entities = grouped_entities.rename(columns={'entity': 'entities'})

grouped_entities.head()

   ID     role                                           entities
0   0   victim                        people who are unscientific
1   0  villain                                  climate alarmists
2   2   victim                                           the U.S.
3   2  villain  climate alarmism; Democratic New York Rep. Ale...
4   3   victim                            a city built on a swamp

In [22]:
grouped_entities.loc[3].entities

"climate alarmism; Democratic New York Rep. Alexandria Ocasio; Democratic New York Rep. Alexandria Ocasio-Cortez's"

In [13]:
# 426 news articles

grouped_entities.ID.nunique()

426

In [14]:
# distribution per narrative roles. Not as imbalanced as I would have expected, luckily

grouped_entities.role.value_counts()

role
villain    406
victim     333
hero       303
Name: count, dtype: int64

In [15]:
roles_df.shape[0]

1687

In [16]:
grouped_entities.shape[0]

1042

Save grouped_entities to data/interim

In [ ]:
grouped_entities.to_csv(
    '../data/interim/grouped_entities.tsv', 
    sep='\t',     
    index=False)